// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: schema_src/payload.proto

package schema

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Payload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stale   *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=Stale,proto3" json:"Stale,omitempty"`
	Payload string                 `protobuf:"bytes,2,opt,name=Payload,proto3" json:"Payload,omitempty"`
}

func (x *Payload) Reset() {
	*x = Payload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_src_payload_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_schema_src_payload_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_schema_src_payload_proto_rawDescGZIP(), []int{0}
}

func (x *Payload) GetStale() *timestamppb.Timestamp {
	if x != nil {
		return x.Stale
	}
	return nil
}

func (x *Payload) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

var File_schema_src_payload_proto protoreflect.FileDescriptor

var file_schema_src_payload_proto_rawDesc = []byte{
	0x0a, 0x18, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x5f, 0x73, 0x72, 0x63, 0x2f, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x63, 0x61, 0x63, 0x68,
	0x65, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x55, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x30, 0x0a,
	0x05, 0x53, 0x74, 0x61, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x05, 0x53, 0x74, 0x61, 0x6c, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x09, 0x5a, 0x07, 0x73, 0x63, 0x68,
	0x65, 0x6d, 0x61, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_schema_src_payload_proto_rawDescOnce sync.Once
	file_schema_src_payload_proto_rawDescData = file_schema_src_payload_proto_rawDesc
)

func file_schema_src_payload_proto_rawDescGZIP() []byte {
	file_schema_src_payload_proto_rawDescOnce.Do(func() {
		file_schema_src_payload_proto_rawDescData = protoimpl.X.CompressGZIP(file_schema_src_payload_proto_rawDescData)
	})
	return file_schema_src_payload_proto_rawDescData
}

var file_schema_src_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_schema_src_payload_proto_goTypes = []interface{}{
	(*Payload)(nil),               // 0: cache.Payload
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_schema_src_payload_proto_depIdxs = []int32{
	1, // 0: cache.Payload.Stale:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_schema_src_payload_proto_init() }
func file_schema_src_payload_proto_init() {
	if File_schema_src_payload_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_schema_src_payload_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Payload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_schema_src_payload_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schema_src_payload_proto_goTypes,
		DependencyIndexes: file_schema_src_payload_proto_depIdxs,
		MessageInfos:      file_schema_src_payload_proto_msgTypes,
	}.Build()
	File_schema_src_payload_proto = out.File
	file_schema_src_payload_proto_rawDesc = nil
	file_schema_src_payload_proto_goTypes = nil
	file_schema_src_payload_proto_depIdxs = nil
}
